# Model parameters - Gradient Boosted Trees
gbt_0: 
  type: gbt
  percent: 1
  learning_rate: 0.1
  depth: 10
  iterations: 1000
  min_data_in_leaf: 5

# Model parameters - xgboost
xgb_0:
  type: xgb
  percent: 0.05
  learning_rate: 0.1
  max_depth: 5
  colsample_bytree: 0.8 
  n_estimators: 100 
  
# Model parameters - random_forest
rf_0:
  type: rf
  percent: 0.05
  n_estimators: 100
  max_features: 'sqrt'
  criterion: 'gini'
  max_depth: 20
  min_samples_split: 2
  min_samples_leaf: 1
  random_state: 42
